### ISSUE TITLE
RuntimeException android 12

### ISSUE THREAD

**Issue by andrei-shevelev** [mapbox/mapbox-search-android#44] opened 2022-06-06 15:04 UTC
## Environment

- Android OS version: Android 12
- Devices affected: Samsung s20 FE
- Search SDK Version: 1.0.0-beta.30
- Mapbox Version: 10.5.0
- Included in project Maps SDK, Nav SDK versions if available:

## Code examples

`MapboxSearchSdk.initialize(this, getKey())`

## Observed behavior and steps

`2022-06-06 17:44:31.092 13808-13808/app.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.test:mapobject, PID: 13808
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.common.EventsService.initialize(com.mapbox.common.EventsServiceOptions) (tried Java_com_mapbox_common_EventsService_initialize and Java_com_mapbox_common_EventsService_initialize__Lcom_mapbox_common_EventsServiceOptions_2)
        at com.mapbox.common.EventsService.initialize(Native Method)
        at com.mapbox.common.EventsService.<init>(EventsService.java:15)
        at com.mapbox.search.analytics.SearchEventsService.<init>(SearchEventsService.kt:18)
        at com.mapbox.search.MapboxSearchSdk.initializeInternal$mapbox_search_android_release(MapboxSearchSdk.kt:214)
        at com.mapbox.search.MapboxSearchSdk.initializeInternal$mapbox_search_android_release$default(MapboxSearchSdk.kt:155)
        at com.mapbox.search.MapboxSearchSdk.initialize(MapboxSearchSdk.kt:142)
        at com.mapbox.search.MapboxSearchSdk.initialize$default(MapboxSearchSdk.kt:133)
        at app.AppContext.onCreate(AppContext.kt:127)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

## Expected behavior

When using the search sdk and maps together on the latest versions, the application crashes
If you disable the initialization of the search sdk, then everything is ok
Normal operation of the application is expected

**Comment by DzmitryFomchyn** [comment] 2022-06-07 20:02
Hey @andrei-shevelev,

> Mapbox Version: 10.5.0

Do you mean Mapbox Maps SDK here?

> ANR android 12

The log you attached is not about ANR. Did you mean other crash in the title?

**Comment by andrei-shevelev** [comment] 2022-06-10 08:59
> Hey @andrei-shevelev,
> 
> > Mapbox Version: 10.5.0
> 
> Do you mean Mapbox Maps SDK here?
> 
> > ANR android 12
> 
> The log you attached is not about ANR. Did you mean other crash in the title?

Yes I meant Mapbox Maps SDK
That's right, it's not ANR, it's RuntimeException

**Comment by DzmitryFomchyn** [comment] 2022-06-10 20:51
@andrei-shevelev,
Do you force any mapbox related libraries to a specific version? From the crash log it seems that the issue is in incompatibility of a common SDK that is used in both Search and Maps SDK.

Check Search SDK sample app https://github.com/mapbox/mapbox-search-android/tree/v1.0.0-beta.30, it uses Maps SDk 10.5.0. I'm curious if it works on your device.

**Comment by DzmitryFomchyn** [comment] 2022-06-24 21:13
@andrei-shevelev,
Any updates here, do you still can see this crash? Waiting for the details.

**Comment by DzmitryFomchyn** [comment] 2022-07-04 11:58
I'm going to close this issues as there's no reply.
It seems that the the reason is with SDK versions incompatibility. Mapbox SDKs are compatible only if used Common SDK versions are compatible by SEMVER rules. Used in the SDK Common SDK versions are specified in release notes:
- Search SDK https://github.com/mapbox/mapbox-search-android/releases
- Nav SDK https://github.com/mapbox/mapbox-navigation-android/releases
- Maps SDK https://github.com/mapbox/mapbox-maps-android/releases

**Comment by andrei-shevelev** [comment] 2022-07-04 12:49
> @andrei-shevelev, Do you force any mapbox related libraries to a specific version? From the crash log it seems that the issue is in incompatibility of a common SDK that is used in both Search and Maps SDK.
> 
> Check Search SDK sample app https://github.com/mapbox/mapbox-search-android/tree/v1.0.0-beta.30, it uses Maps SDk 10.5.0. I'm curious if it works on your device.

In the sample application from this repository everything works correctly, I switched to different commits 1.0.0-beta.30...1.0.0-beta.32
We can also say that there is no deliberate downgrade or upgrade of mapbox libraries in our project. Although I tried to solve this problem this way, unsuccessfully.

**Comment by andrei-shevelev** [comment] 2022-07-04 12:52
> I'm going to close this issues as there's no reply. It seems that the the reason is with SDK versions incompatibility. Mapbox SDKs are compatible only if used Common SDK versions are compatible by SEMVER rules. Used in the SDK Common SDK versions are specified in release notes:
> 
> * Search SDK https://github.com/mapbox/mapbox-search-android/releases
> * Nav SDK https://github.com/mapbox/mapbox-navigation-android/releases
> * Maps SDK https://github.com/mapbox/mapbox-maps-android/releases
> 
> Also, the reason might be similar to what's described in this issue [mapbox/mapbox-maps-android#1173 (comment)](https://github.com/mapbox/mapbox-maps-android/issues/1173#issuecomment-1062707575).

I tried combinations of exactly compatible sdks from your example. The solution described in another issue was also tried.
Perhaps some configuration of our project makes it break, something in the compatibility of libraries. I'll let you know when I can reproduce this on some other example.

**Comment by DzmitryFomchyn** [comment] 2022-07-04 14:13
Thanks for the reply!
It would be very helpful if you could create a minimum project that shows this error.

**Comment by andrei-shevelev** [comment] 2022-07-06 13:03
> I'm going to close this issues as there's no reply. It seems that the the reason is with SDK versions incompatibility. Mapbox SDKs are compatible only if used Common SDK versions are compatible by SEMVER rules. Used in the SDK Common SDK versions are specified in release notes:
> 
> * Search SDK https://github.com/mapbox/mapbox-search-android/releases
> * Nav SDK https://github.com/mapbox/mapbox-navigation-android/releases
> * Maps SDK https://github.com/mapbox/mapbox-maps-android/releases
> 
> Also, the reason might be similar to what's described in this issue [mapbox/mapbox-maps-android#1173 (comment)](https://github.com/mapbox/mapbox-maps-android/issues/1173#issuecomment-1062707575).

I tried to create a similar configuration in a small project, and everything worked correctly for me. Then I started trying again all the tips from the mapbox repositories to fix similar problems. And it looks like the problem was in the initialization order of the component. Perhaps the first time I did not apply this advice carefully enough, but the second time the problem was fixed.
As a result, as you wrote, the solution was to manage the initialization of the mapbox component manually.
(https://github.com/mapbox/mapbox-maps-android/issues/1173#issuecomment-1062707575)

**Comment by andrei-shevelev** [comment] 2022-07-06 13:04
Thank you, I think you can close the issue

**Comment by DzmitryFomchyn** [comment] 2022-07-22 20:24
Thanks for checking!

**Closed by DzmitryFomchyn** 2022-07-22 20:24 UTC
Labels: bug
